name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  run_regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install python module
        run: |
          python -m pip install --upgrade pip
          pip install pytest pandas openpyxl

      - name: Run pytest
        run: |
          export PYTHONPATH=$(pwd)
          pytest -v -s
          
          
